import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/Header";

export const metadata: Metadata = {
  title: "Kickstart-Dapp",
  description: "Generated by create next app",
  icons: {
    icon: "/image/favicon.ico",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fr">
      <body className="bg-gradient-to-r to-violet-800  from-fuchsia-950">
        <Header />
        <main className="my-0 py-16 px-10">{children}</main>
      </body>
    </html>
  );
}
